### ISSUE TITLE
Create sample csv for endyear

### ISSUE THREAD

**Issue by DonMischo** [SergelsOrg/csv2tex#101]
create a full sample csv for endyear, containing competencies for all subjects and a number of workshops and a motivation text

**Comment by DonMischo** [comment]
[competencies5_2021.csv](https://github.com/SergelsOrg/csv2tex/files/8259176/competencies5_2021.csv)

**Comment by ArchibaldBienetre** [comment]
This is what https://github.com/SergelsOrg/csv2tex/pull/97 is for, I take it? @DonMischo
