### ISSUE TITLE
Clarity for csv files

### ISSUE THREAD

**Issue by DonMischo** [SergelsOrg/csv2tex#102]
empty column after subjects

- some colleagues aren't able to read instructions

**Comment by ArchibaldBienetre** [comment]
So, this is not about elective subjects (https://github.com/SergelsOrg/csv2tex/issues/36), this is about fully empty columns?

So, we would just need to "trim" the empty columns to the right of the data?

**Comment by ArchibaldBienetre** [comment]
I'll make a proposal :mag:

**Comment by ArchibaldBienetre** [comment]
This will be a bit tricky, until we convert all CSVRecord:s used in the production code to proper List<String>.

I'll need a bit more time here.
