### ISSUE TITLE
README: Add description of assumed place holder format

### ISSUE THREAD

**Issue by DonMischo** [SergelsOrg/csv2tex#16]
CSV:

Feldtrenner: Komma ,
Zeichenkettentrenner: Anführungszeichen "
UTF8

Beispiel: "Mathematik","Beschreibung",3,,,,

place holder: 
Hashtag + Bezeichnung in Caps
Beispiel: #MATHEMATIK

**Comment by ArchibaldBienetre** [comment]
:information_source: For version 1.0.0 we are now working with fixed placeholders. 

We should documen these alongside the CSV documentation from https://github.com/SergelsOrg/csv2tex/issues/66
