### ISSUE TITLE
Diagram

### ISSUE THREAD

**Issue by DonMischo** [SergelsOrg/csv2tex#29]
first version of diagram, incomplete

will be updated as work continues or new ideas emerge

![csv2tex](https://user-images.githubusercontent.com/89772758/144623808-c7d1a628-40df-4912-8f1d-1ba47b43c420.png)

**Comment by ArchibaldBienetre** [comment]
I had something like this in mind, and intend to add it to the README or another markdown file in the repo
![csv2tex](https://user-images.githubusercontent.com/16072586/154726305-9bc2bf05-1c2b-4e7a-8093-0ac28a68a3b1.svg)
[diagrams.zip](https://github.com/SergelsOrg/csv2tex/files/8098942/diagrams.zip)

(used http://demo.bpmn.io/s/start to create it)
